package com.example.libros.modelo;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Document(collection = "books")
@Data
@AllArgsConstructor
@NoArgsConstructor


public class libro {

    @Id
    private String titulo;
    private String autor;
    private String id;
    private String genero;
    private int anio;
    private int precio;

    // Constructor is generated by Lombok's @AllArgsConstructor

    public String getTitulo() {
        return titulo;
    }

    public String getAutor() {
        return autor;
    }

    public String getIsbn() {
        return id;
    }

    public String getGenero() {
        return genero;
    }

    public int getAnio() {
        return anio;
    }

    public int getPrecio() {
        return precio;
    }
}
